### ISSUE TITLE
Support for PHP5.6?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [ksassnowski/laravel-shareable-models#1]
Any plans to support still widely used PHP 5.6 please?

**Comment by ksassnowski** [comment]
I'm afraid this is a non trivial change. The main issue is that the `vinka/hashids` dependencies dropped support for PHP 5.6 in the [same release](https://github.com/vinkla/laravel-hashids/releases/tag/3.1.0) that they started supporting Laravel 5.4. That means there is no combination with the current dependencies where I can support Laravel `^5.4` and PHP 5.6 at the same time.

The only solution I could think of is to instead use `ivanakimov/hashids` directly instead of the Laravel package since that package actually still supports PHP 5.6. I'll look into it but can't give you an ETA yet.

**Comment by ksassnowski** [comment]
Ok, disregard my above comment. Turns out I'm an idiot.

I'm pulling in `vinkla/hashids` but don't use it anywhere. Instead I always use the original `hashids/hashids` package directly. Meaning that if I simply change my dependencies from `vinkla/hashids` to `hashids/hashids` I can actually support PHP 5.6.

I still need to test it a bit more thoroughly but I think you can expect a new release today or tomorrow.

**Comment by ksassnowski** [comment]
Check out the [1.3.0 release](https://github.com/ksassnowski/laravel-shareable-models/compare/1.2.0...1.3.0).

**Comment by sarfraznawaz2005** [comment]
@ksassnowski awesome thanks :) I think manual also needs update that it  supports 5.6. Thanks again
