### ISSUE TITLE
[Question] Best Practice

### ISSUE THREAD

**Issue by johannesschobel** [ksassnowski/laravel-shareable-models#5]
Dear Kai,

thank you so much for this awesome piece of code - it is really helpful and i managed to implement it in my current api project. However, I have a question regarding "best practice" with this package. Maybe you can help or give advice?

Consider the following (simplified) example of a car customizer (we take `Car` as a resource that is customized and to be shared)
1) A `User` creates a new resource (e.g., a `Car`) and starts adapting it. Thereby, several properties of `Car` are changed during run time (e.g., the `color`, `engine`, `...`) and stored in the database.
2) The user can then generate a `shortcode` (i.e., a `shareable-link`) to the model (`Car`) that he created in order to send it to friends, or continue configuring it another day.

Specific questions here are:
1) What would be your "go to" strategy in order to generate exactly one `shareable_link` for the `Car` model (e.g., I dont want to have multiple links "pointing" to the same model). Probably the link should be created when creating the `Car` model.
2) How can you directly "show" the link to the user that he is able to send the link via e-mail to his friends. How would you "represent" this in the database and model-layer? You would need to have an additional `sharelink_id` field in the `cars` table (and `Car` model respectively). And (as described in 1) automatically link them when creating the `Car`? Or is there another way of "navigating back" (from `Car` to the `ShareLink`?)

Thank you for your time & help,
Best,
Johannes

**Comment by ksassnowski** [comment]
> What would be your "go to" strategy in order to generate exactly one shareable_link for the Car model (e.g., I dont want to have multiple links "pointing" to the same model). Probably the link should be created when creating the Car model.

In your particular case you could create some kind of Factory object to create a `Car` object. Inside the factory method you would then create the shareable link as well. Then every time you want to create a `Car` instance you would use the factory. That would ensure that you can't create a `Car` without also creating a shareable link for it as well.

```php
<?php

class CarFactory
{
    public static function create(array $attributes = []): Car
    {
        $car = Car::create($attributes);

        // Configure the link however you need here.
        ShareableLink::buildFor($car)->setActive()->build();

        return $car;
    }
}
```

Then instead of doing something like `Car::create(...)` you would use `CarFactory::create(...)` instead. Basically delegate the responsibility of upholding that invariant to a dedicated object.

Another more "Laravel" kind of idea would be to hook into the model events, specifically the `created` event (https://laravel.com/docs/5.5/eloquent#events).

To ensure that only one link ever exists for a model I would go for the simplest possible way until that's insufficient. The simplest way I could think of is to simply not expose the ability to manually create a shareable link to the user. So the only way a link gets created for a car is inside the factory.

> How can you directly "show" the link to the user that he is able to send the link via e-mail to his friends.

If you have decided that in your app models can only ever have one shareable link associated with them you could just add a method to your model that looks something like this.

```php
<?php

class Car extends Model implements ShareableInterface
{
    use Shareable;

    public function getShareableLink(): ?ShareableLink
    {
        // Treat the one-to-many relationship like a one-to-one
        // relationship by always grabbing the first link. Instead
        // of returning the entire ShareableLink model you could
        // also directly return the url.
        return $this->links()->first();
    }
}
```

Again, choosing the simplest solution until it no longer suffices. Only then try to come up with more sophisticated solutions.

Hope that helps you!

_Note: I haven't tested the code snippets so they might require some tweaking._

**Comment by johannesschobel** [comment]
Hey there, thank you very much for your (very detailed) answer..

In my application, i am using `L5-Repository` that applies the repository pattern to all models. However, i am not sure, if i can hook into it to automatically create the `ShareLink` as well...

Need to think it through - but i can let you know, which way i selected (and why).

**Comment by ksassnowski** [comment]
I'm closing this for now. Feel free to reopen if you have any other questions.
